events {}

http {
    upstream api_backend { server api:8080; }
    upstream web         { server web:80; }
    upstream admin_panel { server admin:80; }

    server {
        listen 80;
        server_name orthopedic.example.com;

        location /api/ {
            proxy_pass http://api_backend;
        }
        location / {
            proxy_pass http://web;
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 80;
        server_name admin.orthopedic.example.com;

        location /api/ {
            proxy_pass http://api_backend;
        }
        location / {
            proxy_pass http://admin_panel;
        }
    }
}
